name: Cloudflare Pages Cleanup
description: Delete old Cloudflare Pages deployments by environment
inputs:
  environment:
    required: true
  keep_count:
    required: true
  project_name:
    required: true
  api_token:
    required: true
  account_id:
    required: true
runs:
  using: composite
  steps:
    -name: Run cleanup - ${{input.environment}}
    -uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    -run: |
      python scripts/cleanup-deployments.py \
        --environment "${{ inputs.environment }}" \
        --count "${{ inputs.keep_count }}"
    env:
      CLOUDFLARE_API_TOKEN: ${{ inputs.api_token }}
      CLOUDFLARE_ACCOUNT_ID: ${{ inputs.account_id }}
      CLOUDFLARE_PROJECT_NAME: ${{ inputs.project_name }}
    shell: bash
