name: Cleanup Cloudflare deployments

on:
  push:
    branches:
      - development-cloudflare-pages
      - cloudflare-pages
      - dev-cloudflare-deployments-cleanup
  workflow_dispatch:
    inputs:
      target:
        description: "Cleanup target (preview|production)"
        required: true
        default: "preview"
        type: choice
        options: ["preview", "production"]

permissions:
  contents: read

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_PROJECT_NAME: publii-glass-card-company-theme

jobs:
  cleanup-preview:
    name: Cleanup (preview)
    runs-on: ubuntu-latest
    # Run on preview branches or manual input=preview
    if: |
      (github.event_name == 'push' && (
        github.ref == 'refs/heads/development-cloudflare-pages' ||
        github.ref == 'refs/heads/dev-cloudflare-deployments-cleanup'
      )) || (github.event_name == 'workflow_dispatch' &&
             github.event.inputs.target == 'preview')

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-preview
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests python-dateutil

      - name: Run cleanup (preview)
        env:
          CLEANUP_ENVIRONMENT: preview
          CLEANUP_KEEP_COUNT: "1"
        run: |
          python scripts/cleanup-deployments.py \
            --environment "${CLEANUP_ENVIRONMENT}" \
            --count "${CLEANUP_KEEP_COUNT}"

  cleanup-production:
    name: Cleanup (production)
    runs-on: ubuntu-latest
    # Run on prod branch or manual input=production
    if: |
      (github.event_name == 'push' &&
       github.ref == 'refs/heads/cloudflare-pages') ||
      (github.event_name == 'workflow_dispatch' &&
       github.event.inputs.target == 'production')

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-production
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests python-dateutil

      - name: Run cleanup (production)
        env:
          CLEANUP_ENVIRONMENT: production
          CLEANUP_KEEP_COUNT: "1"
        run: |
          python scripts/cleanup-deployments.py \
            --environment "${CLEANUP_ENVIRONMENT}" \
            --count "${CLEANUP_KEEP_COUNT}"
